config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users, only: %i[index show edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :username,
      presence: true,
      format: { with: /\A(?=.*[a-z])[a-z\d]+\Z/i },
      uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    added_attrs = %i[email username full_name phone_number]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:sign_in, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private
  def user_params
    params.require(:user).permit(:username, :full_name,
                                :about, :email, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Realgram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="#">
            <span class="fa-stack my-class">
              <i class="fas fa-circle fa-stack-2x"></i>
              <i class="fas fa-camera fa-inverse fa-stack-1x"></i>
            </span>
            Instagram
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
            <a href="<%= user_path(current_user)%>">
              <i class="fa fa-user"></i>
            </a>
          <% else %>
            <a href="<%= new_user_session_path%>"">
              <i class="fa fa-sign-in"></i>
            </a>
          <% end %>
        </div>
      </div>
    </nav>
    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>
    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2018 INSTAGRAM </p>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/shared/_devisemes.html.erb
<% if resource.errors.any? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-auto">
        <a href="" class="nav-item nav-link" href="#">ABOUT US</a>
        <a href="" class="nav-item nav-link" href="#">SUPPORT</a>
        <a href="" class="nav-item nav-link" href="#">BLOG</a>
        <a href="" class="nav-item nav-link" href="#">PRESS</a>
        <a href="" class="nav-item nav-link" href="#">API</a>
        <a href="" class="nav-item nav-link" href="#">JOB</a>
        <a href="" class="nav-item nav-link" href="#">PRIVACY</a>
        <a href="" class="nav-item nav-link" href="#">TERMS</a>
        <a href="" class="nav-item nav-link" href="#">DIRECTORY</a>
        <a href="" class="nav-item nav-link" href="#">LANGUAGE</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "Icon", authenticated_root_path, class: "navbar-brand core-sprite hide-text" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_tag users_path, method: :get, class: "form-inline my-2 my-lg-0 ml-md-auto", id: "users-search",
        remote: true do %>
        <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2 text-center common-btn",
          placeholder: "Search", autocomplete: "off" %>
        <div id="users-result"></div>
      <% end %>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <a class="nav-link core-sprite explore-icon hide-text" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link core-sprite notification-icon hide-text" href="#"></a>
        </li>
        <li class="nav-item">
          <%= link_to "", destroy_user_session_path, method: :delete,
        class: "nav-link core-sprite profile-icon hide-text" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <img class="avatar" src="https://instuigram-avatar.jpg">
          </div>
          <div class="col-sm-9">
            <h2 class="username"><%= current_user.username %></h2>
            <a class="change-photo" href="">Change Profile Photo</a>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :full_name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :full_name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :about, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :about, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :phone_number, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :phone_number, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <img src="https://instuigram-avatar.jpg">
      </div>
    </div>
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= current_user.username %></h2>
        <a class="edit-profile" href="<%= edit_user_path(current_user) %>">
          <button>Edit Profile</button>
        </a>
      </div>
      <% if user_signed_in? %>
        <a href="<%= destroy_user_session_path%>" data-method="delete">
          <i class="fa fa-user"></i>
        </a>
      <% end %>
      <ul class="posts">
        <li><span>12</span> posts</li>
        <li><span>195</span> followers</li>
        <li><span>345</span> following</li>
      </ul>
      <h2 class="name"><%= current_user.full_name %></h2>
      <div class="user-tabs">
        <a class="tab active" href="">
          <i class="fa fa-th"></i>
          POSTS
        </a>
        <a class="tab" href="">
          <i class="fa fa-tv"></i>
          IGTV
        </a>
        <a class="tab" href="">
          <i class="fa fa-bookmark"></i>
          SAVED
        </a>
        <a class="tab" href="">
          <i class="fa fa-tag"></i>
          TAGGED
        </a>
      </div>
      <div class="user-images">
        <div class="wrapper">
          <img src="your_image_url">
        </div>
        <div class="wrapper">
          <img src="your_image_url">
        </div>
        <div class="wrapper">
          <img src="your_image_url">
        </div>
      </div>
    </div>
  </div>
</div>